---
- name: 'Create compose file'
  template:
    src:   'docker-compose.yml.j2'
    dest:  '{{ es_comrade_compose_path }}'
    owner: 'dockremap'
    group: 'docker'
    mode:  '0o644'

- name: 'Create containers'
  community.docker.docker_compose_v2:
    project_src: '{{ es_comrade_service_path }}'
    pull:        '{{ compose_pull }}'
    state:       '{{ compose_state }}'
    recreate:    '{{ "always" if clusters_config_files.changed else compose_recreate }}'
