---
- name: 'Create compose file'
  template:
    src:   'docker-compose.yml.j2'
    dest:  '{{ es_comrade_compose_path }}'
    owner: 'dockremap'
    group: 'docker'
    mode:   0644

- name: 'Create containers'
  community.docker.docker_compose_v2:
    project_src: '{{ es_comrade_service_path }}'
    recreate:    '{{ compose_recreate) }}'
    state:       '{{ clusters_config_files.changed | ternary("restarted", compose_state) }}'
    pull:        '{{ compose_pull }}'
